### ISSUE TITLE
Fix Endlessids Compat

### ISSUE THREAD

**Issue by quentin452** [quentin452/TragicMC2-Continuation#1]
```
[04:15:30] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2257) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:2572) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2329) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the biome array of a chunk like in vanilla! Crashing in fear of potential world corruption!
Please report this issue on https://github.com/FalsePattern/EndlessIDs ASAP!
	at net.minecraft.world.chunk.Chunk.emergencyCrash(Chunk.java:1628) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zbn000$endlessids$crashSetBiomeArray(Chunk.java:1635) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_76616_a(Chunk.java) ~[apx.class:?]
	at tragicneko.tragicmc.worldgen.SynapseVariantGen.generate(SynapseVariantGen.java:60) ~[SynapseVariantGen.class:?]
	at tragicneko.tragicmc.dimension.SynapseChunkProvider.func_73153_a(SynapseChunkProvider.java:440) ~[SynapseChunkProvider.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:174) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313) ~[oi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404) ~[nh.class:?]
	at lotr.common.LOTRNetHandlerPlayServer.func_147347_a(LOTRNetHandlerPlayServer.java:123) ~[LOTRNetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more

**Comment by quentin452** [comment]
workaround : disabling allowSynapseVariants in TragicMC.cfg to fix the crash
